font_family Iosevka
font_size 18.0
disable_ligatures always
font_features Iosevka -calt -liga -dlig
enabled_layouts grid
tab_bar_edge top
tab_bar_align center
tab_separator " | "
tab_title_template "{active_session_name}{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}: {tab.last_focused_progress_percent}{title}"
background_opacity 0.95
background_blur 1
allow_remote_control socket-only
listen_on unix:@dankitty
notify_on_cmd_finish invisible
macos_option_as_alt yes

# smart-splits.nvim
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+h neighboring_window left
map alt+l neighboring_window right
map --when-focus-on var:IS_NVIM alt+j
map --when-focus-on var:IS_NVIM alt+k
map --when-focus-on var:IS_NVIM alt+h
map --when-focus-on var:IS_NVIM alt+l

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab 10

map kitty_mod+enter launch --cwd=current
# sessions
map alt+f goto_session

# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME
